### ISSUE TITLE
SSL error when reconnecting

### ISSUE THREAD

**Issue by chrisportela** [jhgg/jeev#12]
I figured this would be the best place to keep this.

I've made changes so that Jeev tries to reconnect after a websocket connection is closed (When it gets a ConnectionAlreadyClosed(?) exception from the websocket client slack uses), but it seems to have gotten an SSL error now on the reconnect.

```
ERROR:jeev.adapter.slack:WebSocket connection closed.
Traceback (most recent call last):
  File "/home/ubuntu/jeev-pt/local/lib/python2.7/site-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/ubuntu/jeev-pt/local/lib/python2.7/site-packages/jeev-0.3.0b0-py2.7.egg/jeev/adapter/slack.py", line 340, in _run
    self._do_slack_connection()
  File "/home/ubuntu/jeev-pt/local/lib/python2.7/site-packages/jeev-0.3.0b0-py2.7.egg/jeev/adapter/slack.py", line 355, in _do_slack_connection
    frame = self._server.websocket.recv()
  File "/home/ubuntu/jeev-pt/local/lib/python2.7/site-packages/websocket_client-0.32.0-py2.7.egg/websocket/_core.py", line 348, in recv
    opcode, data = self.recv_data()
  File "/home/ubuntu/jeev-pt/local/lib/python2.7/site-packages/websocket_client-0.32.0-py2.7.egg/websocket/_core.py", line 365, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/home/ubuntu/jeev-pt/local/lib/python2.7/site-packages/websocket_client-0.32.0-py2.7.egg/websocket/_core.py", line 378, in recv_data_frame
    frame = self.recv_frame()
  File "/home/ubuntu/jeev-pt/local/lib/python2.7/site-packages/websocket_client-0.32.0-py2.7.egg/websocket/_core.py", line 410, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/home/ubuntu/jeev-pt/local/lib/python2.7/site-packages/websocket_client-0.32.0-py2.7.egg/websocket/_abnf.py", line 300, in recv_frame
    self.recv_header()
  File "/home/ubuntu/jeev-pt/local/lib/python2.7/site-packages/websocket_client-0.32.0-py2.7.egg/websocket/_abnf.py", line 249, in recv_header
    header = self.recv_strict(2)
  File "/home/ubuntu/jeev-pt/local/lib/python2.7/site-packages/websocket_client-0.32.0-py2.7.egg/websocket/_abnf.py", line 334, in recv_strict
    bytes = self.recv(min(16384, shortage))
  File "/home/ubuntu/jeev-pt/local/lib/python2.7/site-packages/websocket_client-0.32.0-py2.7.egg/websocket/_core.py", line 476, in _recv
    return recv(self.sock, bufsize)
  File "/home/ubuntu/jeev-pt/local/lib/python2.7/site-packages/websocket_client-0.32.0-py2.7.egg/websocket/_socket.py", line 77, in recv
    bytes = sock.recv(bufsize)
  File "/home/ubuntu/jeev-pt/local/lib/python2.7/site-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/_ssl2.py", line 204, in recv
    return self.read(buflen)
  File "/home/ubuntu/jeev-pt/local/lib/python2.7/site-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/_ssl2.py", line 109, in read
    return self._sslobj.read(len)
SSLError: [Errno 2] _ssl.c:1429: The operation did not complete (read)
<Greenlet at 0x7f0f3c580730: <bound method SlackAdapter._run of <jeev.adapter.slack.SlackAdapter object at 0x7f0f3d0c8c90>>> failed with SSLError
```

**Comment by jhgg** [comment]
Sounds like an issue with the remote. I'd just try again, with an exponential backoff until a connection is able to be established.
